-- AlterTable
ALTER TABLE "GeneralInformation" ADD COLUMN     "lessIdcd" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "lessSecurityHeld" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "provision" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "subTotal" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN     "total" DOUBLE PRECISION DEFAULT 0,
ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "status" SET DEFAULT 'new';
